config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'items#index'
  resources :items
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :items
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_index, except: :index

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    Item.create(name: item_params[:name],price: item_params[:price], user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  private

  def item_params
    params.require(:item).permit(:name, :price)
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # @items = Item.where(user_id: current_user.id)
    @user = User.find(current_user.id)
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/create.html.erb
<h1>購入が完了しました</h1>
<%= link_to "購入一覧", items_path %>

app/views/items/index.html.erb
<h1>購入商品</h1>
<% if user_signed_in? %>
  <% @items.each do |item| %>
    <p><%= item.name %>:<%= item.price %>:<%= item.user.nickname.present? ? "購入者 #{item.user.nickname}" : "会員No.#{item.user.id}" %></p>
  <% end %>
<% else %>
  <p>ログインしてください</p>
<% end %>

app/views/items/new.html.erb
<%= form_for @item, medhod: :post do |f| %>
  <h1>ご購入の商品情報を入力</h1>
  <p>商品名: <%= f.text_field :name %></p>
  <p>値段: <%= f.text_field :price %></p>
  <input type="submit" value="送信">
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <%= link_to "トップ", items_path %>
      <%= link_to "投稿画面", new_item_path %>
      <%= link_to "マイページへ", user_path(current_user.id) %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path, class: 'post' %>
      <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<% @user.items.each do |item| %>
  <p><%= item.name %>:<%= item.price %></p>
<% end %>